---
- name: deploy front-end load balancers haproxy
  hosts: frontends
  gather_facts: false
  become: true

  tasks:

  - name: install packages httpie and HAProxy
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - httpie
      - haproxy
    tags:
      - install_haproxy

  - name: enable HAProxy
    service:
      name: haproxy
      state: started
    tags:
      enable_haproxy

  - name: configure haproxy
    template:
      src: ./templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart haproxy
    tags:
      - configure_haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
