---
# Configure the database for the application

- name: configure postgres database
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:

  - name: enable postgres to listen externally (default is localhost)
    lineinfile:
      path: /var/lib/pgsql/data/postgresql.conf
      regexp: "^listen_addresses='*'"
      line: "listen_addresses='*'"

  - name: enable postgres to authenticate remote users
    lineinfile:
      path: /var/lib/pgsql/data/pg_hba.conf
      regexp: "^host"
      line: "host    all             all             all                     md5"

# make this a handler!

  - name: restart postgres - after reconfiguration
    service:
      name: postgresql.service
      state: restarted

  - name: install python-psycopg2 module on target - python postgres adapter
    yum:
      name: python-psycopg2
      state: latest

  - name: create ansible_books database
    postgresql_db:
      name: ansible_books
      state: present
      login_user: postgres
    become: yes
    become_user: postgres
    tags: create_database

  - name: copy postgres password copy_create_script
    copy:
      src: ./password.sql
      dest: /tmp/password.sql
    tags:
      - copy_password_sql

  - name: copy create_table sql script
    copy:
      src: ./create_table.sql
      dest: /tmp/create_table.sql
    tags:
      - copy_create_sql

  - name: copy populate_table sql script
    copy:
      src: ./populate_table.sql
      dest: /tmp/populate_table.sql
    tags:
      - copy_populate_sql

  - block:

    - name: set postgres password
      command: psql -d ansible_books -f /tmp/password.sql
      become: yes
      become_user: postgres
      tags:
        - set_postgres_password

    - name: create table
      command: psql -d ansible_books -f /tmp/create_table.sql
      become: yes
      become_user: postgres
      tags:
        - create_table
  #  - name: copy populate_table script

    - name: populate_table
      command: psql -d ansible_books -f /tmp/populate_table.sql
      become: yes
      become_user: postgres
      tags:
        - populate_table

#TODO: 1) Replace above with a loop i.e. call command once
#TODO: 2) Scripts should be read only postgres users
#TODO: 3) Delete scripts after execution
#TODO: 4) Use ansible vault and templates for password.sql
