---
- name: pre-flight, fetch assets from bastion - repo and keys
  hosts: bastion
  gather_facts: false
  become: true
  vars:
    repofile: open_three-tier-app.repo

  tasks:

  - name: fetch repo file
    fetch:
      src: /etc/yum.repos.d/{{repofile}}
      dest: ./templates/{{repofile}}
      flat: yes
    tags:
      - get_repo_file

  - name: fetch user key
    fetch:
      src: /root/.ssh/{{GUID}}key.pem
      dest: ./{{GUID}}key.pem
      flat: yes
    tags:
      - get_user_ssh_key

- name: setup ssh key locally
  hosts: 127.0.0.1
  gather_facts: false

  tasks:

  - name: enable ssh key locally
    copy:
      src: ./{{GUID}}key.pem
      dest: ~/.ssh/{{GUID}}key.pem
      mode: 0400
    tags:
      - enable_ssh_key

  - name: remove copy of ssh key
    file:
      path: ./{{GUID}}key.pem
      state: absent
    tags:
      - remove_ssh_key
