---
- name: install java and compile serverlet
  gather_facts: false
  become: true
  hosts: apps
  tasks:

  - name: install jdk
    yum:
      name:  java-1.8.0-openjdk-devel
      state: latest
    tags:
      - install_jdk

  - name: install postgres jdbc driver
    get_url:
      url: https://jdbc.postgresql.org/download/postgresql-42.1.4.jar
      dest: /usr/share/tomcat/lib/
    tags:
      - install_postgres_jdbc_driver

  - name: install source code in tomcat
    unarchive:
      src: books.gz
      dest: /usr/share/tomcat/webapps
    tags:
      - install_books_sourcepostgresServlet

#TODO: set GUID in context.xml before compiling


  - name: compile book serverlet
    command: javac -classpath /usr/share/tomcat/lib/tomcat-servlet-3.0-api.jar /usr/share/tomcat/webapps/books/WEB-INF/classes/postgresServlet.java
    notify: restart tomcat
    tags:
      - compile_serverlet

  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
