---
- name: Smoke Tests
  gather_facts: false
  hosts: local
  connection: local
#TODO: why isn't this inherited from inventory? connection set to local there?

  tasks:

  - name: check Cfor proper response
    uri:
      url:  http://{{ item.server }}.{{ GUID }}.example.opentlc.com:{{ item.port }}
      return_content: yes
    register: result
    until: '"Tomcat on" in result.content'
#TODO: use a test string variable in previous line
    retries: 10
    delay: 1
    with_items:
      - { server: frontend1, port: "{{HAPROXY_PORT}}" }
      - { server: app1, port:  }
      - { server: app2, port: 8080 }
